### ISSUE TITLE
change organization's default backgroundURL

### ISSUE THREAD

**Issue by mel4ni3** [KnightAssistUCF/KnightAssist-WebApp-UCF-Senior-Design#61]
The default backgroundURL of an organization should be the orgdefaultbackground.png file, not the default profilePicPath which should remain as the gravatar image.[ ](https://github.com/KnightAssistUCF/KnightAssist-WebApp-UCF-Senior-Design/blob/main/backend/models/organization.js)

**Comment by YHmaiti** [comment]
thank you. This is addressed currently as a PR.
